##### Copyright 2019 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TensorFlow 2 quickstart for beginners

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This short introduction uses [Keras](https://www.tensorflow.org/guide/keras/overview) to:

1. Load a prebuilt dataset.
1. Build a neural network machine learning model that classifies images.
2. Train this neural network.
3. Evaluate the accuracy of the model.

This tutorial is a [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.

1. In Colab, connect to a Python runtime: At the top-right of the menu bar, select *CONNECT*.
2. To run all the code in the notebook, select **Runtime** > **Run all**. To run the code cells one at a time, hover over each cell and select the **Run cell** icon.

![Run cell icon](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/images/beginner/run_cell_icon.png?raw=1)

## Set up TensorFlow

Import TensorFlow into your program to get started:

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
If you are following along in your own development environment, rather than [Colab](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb), see the [install guide](https://www.tensorflow.org/install) for setting up TensorFlow for development.

Note: Make sure you have upgraded to the latest `pip` to install the TensorFlow 2 package if you are using your own development environment. See the [install guide](https://www.tensorflow.org/install) for details.

## Load a dataset

Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by `255.0`. This also converts the sample data from integers to floating-point numbers:

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

mnist = tf.keras.datasets.mnist


(x_train, y_train), (x_test, y_test) = mnist.load_data()


print(y_train[0])

# Беремо перше зображення з x_train
image = x_train[0]

# Перетворюємо зображення в діапазон від 0 до 255, якщо це потрібно
image = np.uint8(image)  # перетворюємо в тип uint8

# Перетворюємо зображення в формат PIL
image_pil = Image.fromarray(image)

# Зберігаємо зображення на диск
image_pil.save('image_0.png')  # Зберігаємо у форматі PNG


from google.colab import files

# Завантажуємо файл на локальний комп'ютер
files.download('image_0.png')









11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [4]:
# Нормалізуємо значення
x_train, x_test = x_train / 255.0, x_test / 255.0

## Build a machine learning model

Build a `tf.keras.Sequential` model:

In [5]:
from tensorflow.keras import models, layers, Input

# Визначаємо модель з Input як перший шар
model = models.Sequential([
    Input(shape=(28, 28)),  # Вхідний шар з формою (28, 28)
    layers.Flatten(),  # Розгладжуємо вектор
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')  # Вихідний шар для 10 класів
])

# Модель компілюється і готова до тренування
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

[`Sequential`](https://www.tensorflow.org/guide/keras/sequential_model) is useful for stacking layers where each layer has one input [tensor](https://www.tensorflow.org/guide/tensor) and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the [`Flatten`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten), [`Dense`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense), and [`Dropout`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout) layers.

For each example, the model returns a vector of [logits](https://developers.google.com/machine-learning/glossary#logits) or [log-odds](https://developers.google.com/machine-learning/glossary#log-odds) scores, one for each class.

In [34]:
# Припустимо, x_train містить зображення, а перше зображення має індекс 0.
image = x_train[0]  # вибираємо перше зображення з тренувального набору
image = image.reshape(1, 28, 28)  # перетворюємо в форму (1, 28, 28)

# Модель передбачає логіти (не ймовірності)
predictions = model(image)  # передбачення

print(predictions)

# Якщо результат є логітами, застосовуємо softmax для перетворення в ймовірності
# probabilities = tf.nn.softmax(predictions).numpy()  # застосовуємо softmax для перетворення в ймовірності

# Отримуємо індекс класу з найвищою ймовірністю
# predicted_class = tf.argmax(probabilities, axis=1).numpy()[0]
# print(f'Predicted class: {predicted_class}')

tf.Tensor(
[[0.06928607 0.09167407 0.12509872 0.07336359 0.08007656 0.1521224
  0.08925141 0.11409426 0.06008234 0.14495061]], shape=(1, 10), dtype=float32)


In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.11691748, 0.07781853, 0.1251099 , 0.21860108, 0.02145279,
        0.06328336, 0.10301764, 0.03485105, 0.11985893, 0.11908931]],
      dtype=float32)

The `tf.nn.softmax` function converts these logits to *probabilities* for each class:

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.10156231, 0.09766797, 0.10239778, 0.11243285, 0.09231511,
        0.09625861, 0.10016038, 0.0935603 , 0.1018615 , 0.10178313]],
      dtype=float32)

Note: It is possible to bake the `tf.nn.softmax` function into the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to provide an exact and numerically stable loss calculation for all models when using a softmax output.

Define a loss function for training using `losses.SparseCategoricalCrossentropy`:

In [6]:
import os

# Перевіряємо, чи існує файл
if os.path.exists('image_0.png'):
    print("Файл існує!")
else:
    print("Файл не знайдений!")

Файл існує!


In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.math.log(1/10) ~= 2.3`.

In [8]:
loss_fn(y_train[:1], predictions).numpy()

NameError: name 'predictions' is not defined

Before you start training, configure and compile the model using Keras `Model.compile`. Set the [`optimizer`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers) class to `adam`, set the `loss` to the `loss_fn` function you defined earlier, and specify a metric to be evaluated for the model by setting the `metrics` parameter to `accuracy`.

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Train and evaluate your model

Use the `Model.fit` method to adjust your model parameters and minimize the loss:

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8739 - loss: 0.4362
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9636 - loss: 0.1244
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9764 - loss: 0.0796
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9822 - loss: 0.0584
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9871 - loss: 0.0417


The `Model.evaluate` method checks the model's performance, usually on a [validation set](https://developers.google.com/machine-learning/glossary#validation-set) or [test set](https://developers.google.com/machine-learning/glossary#test-set).

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9788 - loss: 0.0712


[0.07117453217506409, 0.9787999987602234]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533885, 0.08533883, 0.08533948, 0.08535198, 0.08533883,
        0.08533883, 0.08533883, 0.23193635, 0.08533907, 0.08533896],
       [0.0853375 , 0.08533891, 0.2319574 , 0.08534122, 0.0853375 ,
        0.0853375 , 0.0853375 , 0.0853375 , 0.0853375 , 0.0853375 ],
       [0.08534858, 0.23178482, 0.08536041, 0.08535403, 0.0853531 ,
        0.0853489 , 0.08534957, 0.08537363, 0.08537836, 0.08534859],
       [0.23192395, 0.08533961, 0.0853553 , 0.08533961, 0.08533961,
        0.08533961, 0.08534078, 0.0853399 , 0.08533961, 0.08534195],
       [0.08534227, 0.08534198, 0.08534248, 0.08534198, 0.23188639,
        0.08534198, 0.08534246, 0.08535131, 0.08534209, 0.08536704]],
      dtype=float32)>

In [16]:
import numpy as np

# Знаходимо клас з найбільшою ймовірністю для кожного зображення
predicted_classes = np.argmax(probability_model(x_test[:5]), axis=1)

# Виводимо передбачення для кожного зображення
print(predicted_classes)
print(y_test[:5])

[7 2 1 0 4]
[7 2 1 0 4]


## Conclusion

Congratulations! You have trained a machine learning model using a prebuilt dataset using the [Keras](https://www.tensorflow.org/guide/keras/overview) API.

For more examples of using Keras, check out the [tutorials](https://www.tensorflow.org/tutorials/keras/). To learn more about building models with Keras, read the [guides](https://www.tensorflow.org/guide/keras). If you want learn more about loading and preparing data, see the tutorials on [image data loading](https://www.tensorflow.org/tutorials/load_data/images) or [CSV data loading](https://www.tensorflow.org/tutorials/load_data/csv).
